FROM alpine:3.18 as build
LABEL org.opencontainers.image.source = "https://github.com/tez-capital/tezpay"

RUN apk add wget

# Add a build argument for the token
ARG GITHUB_TOKEN

# Create a script for conditional authentication
RUN printf '#!/bin/sh\n\
if [ -z "$GITHUB_TOKEN" ]; then\n\
  wget "$@" \n\
else\n\
  wget --header "Authorization: token $GITHUB_TOKEN" "$@" \n\
fi\n' > /usr/local/bin/auth_wget && chmod +x /usr/local/bin/auth_wget

# Use auth_wget for downloading files with optional authentication
RUN auth_wget https://raw.githubusercontent.com/alis-is/eli/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh
WORKDIR /tezpay-bin
RUN auth_wget https://raw.githubusercontent.com/tez-capital/tezpay/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh

FROM gcr.io/distroless/static-debian12
COPY --from=build /tezpay-bin/tezpay /tezpay-bin/tezpay
COPY --from=build /usr/local/bin/auth_wget /usr/local/bin/auth_wget

WORKDIR /tezpay

ENTRYPOINT [ "/tezpay-bin/tezpay" ]
CMD ["continual"]