FROM alpine:3.17.2

RUN apk add wget
# install eli for minimal extension support
RUN wget -q https://raw.githubusercontent.com/alis-is/eli/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh
WORKDIR /tezpay-bin
# install tezpay
RUN wget -q https://raw.githubusercontent.com/alis-is/tezpay/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh
WORKDIR /tezpay

ENTRYPOINT [ "/tezpay-bin/tezpay" ]
CMD ["continual"]