#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [ "$STAGED_GO_FILES" = "" ]; then
    printf "no go files updated\n"
else
    for file in $STAGED_GO_FILES; do
        go fmt "$file"
		git add "$file"
    done
fi