package core

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/tez-capital/tezpay/common"
	"github.com/tez-capital/tezpay/configuration"
	"github.com/tez-capital/tezpay/state"
	"github.com/tez-capital/tezpay/test/mock"
	"github.com/tez-capital/tezpay/utils"
	"github.com/trilitech/tzgo/tezos"
)

type mockGenerateCollector struct {
	mock.EmptyCollector
}

func (engine *mockGenerateCollector) GetId() string {
	return "mockGenerateCollector"
}

func (engine *mockGenerateCollector) IsRevealed(address tezos.Address) (bool, error) {
	return true, nil
}

func (engine *mockGenerateCollector) GetCycleStakingData(baker tezos.Address, cycle int64) (*common.BakersCycleData, error) {
	rawCycleData := `{"OwnDelegatedBalance":"275708698","ExternalDelegatedBalance":"49100747788","BlockDelegatedRewards":"1197688","IdealBlockDelegatedRewards":"1197688","AttestationsDelegatedRewards":"1920302","IdealAttestationsDelegatedRewards":"1920302","DalDelegatedRewards":"427318","IdealDalDelegatedRewards":"427318","BlockDelegatedFees":"17100","DelegatorsCount":57,"OwnStakedBalance":"16421212933","ExternalStakedBalance":"29383795329","BlockStakingRewardsEdge":"192434","AttestationStakingRewardsEdge":"308534","BlockStakingFees":"0","StakersCount":8,"FrozenDepositLimit":"7300000000","Delegators":[{"Address":"tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE","DelegatedBalance":"18996459719","StakedBalance":"0","Emptied":false},{"Address":"tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL","DelegatedBalance":"16995702660","StakedBalance":"0","Emptied":false},{"Address":"tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng","DelegatedBalance":"6704943203","StakedBalance":"0","Emptied":false},{"Address":"tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb","DelegatedBalance":"2067404437","StakedBalance":"0","Emptied":false},{"Address":"tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb","DelegatedBalance":"767347858","StakedBalance":"0","Emptied":false},{"Address":"tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7","DelegatedBalance":"664759189","StakedBalance":"0","Emptied":false},{"Address":"tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h","DelegatedBalance":"598755901","StakedBalance":"0","Emptied":false},{"Address":"tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv","DelegatedBalance":"507845869","StakedBalance":"0","Emptied":false},{"Address":"tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn","DelegatedBalance":"405103709","StakedBalance":"0","Emptied":false},{"Address":"tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2","DelegatedBalance":"313906924","StakedBalance":"0","Emptied":false},{"Address":"tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj","DelegatedBalance":"170719784","StakedBalance":"0","Emptied":false},{"Address":"tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE","DelegatedBalance":"165652388","StakedBalance":"0","Emptied":false},{"Address":"tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X","DelegatedBalance":"161298995","StakedBalance":"0","Emptied":false},{"Address":"tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi","DelegatedBalance":"94164895","StakedBalance":"0","Emptied":false},{"Address":"tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE","DelegatedBalance":"75318303","StakedBalance":"0","Emptied":false},{"Address":"tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx","DelegatedBalance":"74317010","StakedBalance":"0","Emptied":false},{"Address":"tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW","DelegatedBalance":"70644509","StakedBalance":"0","Emptied":false},{"Address":"tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2","DelegatedBalance":"50000001","StakedBalance":"0","Emptied":false},{"Address":"tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh","DelegatedBalance":"34441415","StakedBalance":"0","Emptied":false},{"Address":"tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm","DelegatedBalance":"32415471","StakedBalance":"0","Emptied":false},{"Address":"tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56","DelegatedBalance":"20256873","StakedBalance":"0","Emptied":false},{"Address":"tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9","DelegatedBalance":"18888009","StakedBalance":"0","Emptied":false},{"Address":"tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA","DelegatedBalance":"17427981","StakedBalance":"0","Emptied":false},{"Address":"tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71","DelegatedBalance":"14207578","StakedBalance":"0","Emptied":false},{"Address":"tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs","DelegatedBalance":"12750656","StakedBalance":"0","Emptied":false},{"Address":"tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y","DelegatedBalance":"11966885","StakedBalance":"0","Emptied":false},{"Address":"tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2","DelegatedBalance":"11307149","StakedBalance":"0","Emptied":false},{"Address":"tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES","DelegatedBalance":"10889299","StakedBalance":"0","Emptied":false},{"Address":"tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6","DelegatedBalance":"7355283","StakedBalance":"0","Emptied":false},{"Address":"tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa","DelegatedBalance":"5221495","StakedBalance":"0","Emptied":false},{"Address":"tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv","DelegatedBalance":"2939210","StakedBalance":"0","Emptied":false},{"Address":"tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB","DelegatedBalance":"1984760","StakedBalance":"0","Emptied":false},{"Address":"tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq","DelegatedBalance":"1866216","StakedBalance":"0","Emptied":false},{"Address":"tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS","DelegatedBalance":"1641573","StakedBalance":"0","Emptied":false},{"Address":"tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF","DelegatedBalance":"1502458","StakedBalance":"0","Emptied":false},{"Address":"tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT","DelegatedBalance":"1459627","StakedBalance":"0","Emptied":false},{"Address":"tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV","DelegatedBalance":"1425001","StakedBalance":"0","Emptied":false},{"Address":"tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo","DelegatedBalance":"1406177","StakedBalance":"0","Emptied":false},{"Address":"tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi","DelegatedBalance":"1322354","StakedBalance":"0","Emptied":false},{"Address":"tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4","DelegatedBalance":"990125","StakedBalance":"0","Emptied":false},{"Address":"tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or","DelegatedBalance":"960009","StakedBalance":"0","Emptied":false},{"Address":"tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq","DelegatedBalance":"370571","StakedBalance":"0","Emptied":false},{"Address":"KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA","DelegatedBalance":"289285","StakedBalance":"0","Emptied":false},{"Address":"tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh","DelegatedBalance":"275000","StakedBalance":"0","Emptied":false},{"Address":"tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S","DelegatedBalance":"200001","StakedBalance":"0","Emptied":false},{"Address":"tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA","DelegatedBalance":"172996","StakedBalance":"0","Emptied":false},{"Address":"KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y","DelegatedBalance":"164629","StakedBalance":"0","Emptied":false},{"Address":"tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v","DelegatedBalance":"162848","StakedBalance":"0","Emptied":false},{"Address":"tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2","DelegatedBalance":"63473","StakedBalance":"0","Emptied":false},{"Address":"tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV","DelegatedBalance":"40787","StakedBalance":"0","Emptied":false},{"Address":"tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj","DelegatedBalance":"27475","StakedBalance":"0","Emptied":false},{"Address":"tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9","DelegatedBalance":"8937","StakedBalance":"0","Emptied":false},{"Address":"KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm","DelegatedBalance":"826","StakedBalance":"0","Emptied":false},{"Address":"tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv","DelegatedBalance":"1","StakedBalance":"0","Emptied":false},{"Address":"tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu","DelegatedBalance":"1","StakedBalance":"0","Emptied":false},{"Address":"KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD","DelegatedBalance":"0","StakedBalance":"0","Emptied":false},{"Address":"KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE","DelegatedBalance":"0","StakedBalance":"0","Emptied":false}]}`
	var cycleData common.BakersCycleData
	err := json.Unmarshal([]byte(rawCycleData), &cycleData)
	if err != nil {
		panic(err)
	}
	return &cycleData, err
}

func Test_Generate(t *testing.T) {
	var err error
	assert := assert.New(t)

	state.Init(".", state.StateInitOptions{})
	rawConfig := `{
        tezpay_config_version: 0
        baker: tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM
        payouts: {
                fee: 0.11
                transaction_fee_buffer: 0
                kt_transaction_fee_buffer: 0
        }
        delegators: {
                requirements: {
                        minimum_balance: 10
                }
        }
        network: {
                rpc_pool: [
					https://eu.rpc.tez.capital/
					https://us.rpc.tez.capital/
                ]
                tzkt_url: https://api.tzkt.io/
        }
        overdelegation: {
                protect: true
        }
        income_recipients: {
                donate: 0.01
        }
        notifications: [
        ]
	}`

	config, _ := configuration.LoadFromString([]byte(rawConfig))
	assert.NotNil(config)

	collector := mockGenerateCollector{}
	signer := mock.InitSimpleSigner()

	engineContext := common.NewGeneratePayoutsEngines(&collector, signer, func(msg string) {})

	result, err := GeneratePayouts(config, engineContext, &common.GeneratePayoutsOptions{
		Cycle: 1016,
	})

	assert.Nil(err)
	assert.NotNil(result)
	fmt.Println(len(result.Payouts))

	var expectedResult common.CyclePayoutBlueprint = common.CyclePayoutBlueprint{
		Cycle:                    1016,
		OwnStakedBalance:         tezos.NewZ(16421212933),
		OwnDelegatedBalance:      tezos.NewZ(275708698),
		ExternalStakedBalance:    tezos.NewZ(29383795329),
		ExternalDelegatedBalance: tezos.NewZ(49100747788),
		EarnedBlockFees:          tezos.NewZ(17100),
		EarnedRewards:            tezos.NewZ(3545308),
		EarnedTotal:              tezos.NewZ(3562408),
		BondIncome:               tezos.NewZ(19693),
		FeeIncome:                tezos.NewZ(385753),
		IncomeTotal:              tezos.NewZ(405446),
		DonatedBonds:             tezos.NewZ(198),
		DonatedFees:              tezos.NewZ(3896),
		DonatedTotal:             tezos.NewZ(4094),
		Payouts: []common.PayoutRecipe{
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1dKeXpumUQD5aCgk3jb7i7psWiRkzqJQdE"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(18996459719),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1219794),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(150761),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1WZRZ6ciwRvkx5YVe5uVXKxrnzDQQevFCL"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(16995702660),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1091322),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(134882),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1WpPaE47vtUT56MZGgKVi4VQCgEF95mvng"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(6704943203),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(430535),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(53212),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2X42QzdRqoqeKCqZaGpoXD4VmzmwbuMJMb"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(2067404437),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(132751),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(16407),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1PABDPXbg9rqz62umCaQ8YhCUajmoYK2Cb"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(767347858),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(49273),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(6089),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1dhJPohjESC3zzRnaJH7krf5wZPwLm4oH7"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(664759189),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(42685),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(5275),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1gnuBF9TbBcgHPV2mUE96tBrW7PxqRmx1h"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(598755901),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(38447),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(4751),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(507845869),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(32610),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(4030),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1XS2hdV3ygveRn1gxRJZgJ4yxFK1YnRrLn"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(405103709),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(26013),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(3214),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1P9A1noGEeoAQ6WNYM87BbJ3iaioorrws2"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(313906924),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(20156),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(2491),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1eYiA2SFVBKPK2UW24puEzbTiLHxMDjVtj"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(170719784),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(10963),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1354),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(165652388),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(10637),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1314),
				Note:             "RECIPIENT_TARGETS_PAYOUT",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1WWvSczbkko8p14qknj6d1KiK4T3ckQ33X"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(161298995),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(10357),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1280),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1gKDahpLhd85yuJ6TEFAwrcnmcEG9gTkSi"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(94164895),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(6046),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(747),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2BZibvVaRzZq5kUWz1rcrJychdbHmoNZJE"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(75318303),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(4837),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(597),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1cXDqHit4wsNv6dFHggKxDUBdpTkAaizyx"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(74317010),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(4772),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(589),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2NvuB26dtjUg11Gb49uocbYrJf26zN2QqW"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(70644509),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(4536),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(560),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1XyRgFTiNNZU7WzG3LDBi1bXWYPupBNBL2"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(50000001),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(3211),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(396),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1dLZQyaopB2MDMdQC5nRt3Yx6RArVRubRh"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(34441415),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(2211),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(273),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1gMRKQWdhY5ZPUehpHofLswyL8Vexvfpbm"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(32415471),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(2081),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(257),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2Lhty58UJvywseQH9vpGasHjuHtiitKZ56"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(20256873),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1301),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(160),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1hVZBTeTs9GZtpShYYuF92f7F2g4gWSQo9"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(18888009),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1213),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(149),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1Nry5YPddf4VFDyunXLR8b8AtpvGJLMLZA"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(17427981),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1119),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(138),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1boUGNrp8Z1WEAkqTHAPr5DennP7tQjF71"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(14207578),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(913),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(112),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1Sf9KWCfjN3nsPHB4cek2MXBuXq5qjBZrs"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(12750656),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(818),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(101),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1frE7ArsC1spvQGizY5gBbJBtjnzGCgQ3y"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(11966885),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(769),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(94),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1hbseHXGm2XB7ivo1r3mbpH29c4GZE1aV2"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(11307149),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(726),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(89),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1f8LD3RZ9SMZUgsHQsQAX85EApD2cTXKES"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(10889299),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(699),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(86),
				IsValid:          true,
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1dTmMLY7tan1HKfW5e3KxJcfZput6UuTH6"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(7355283),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(472),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(58),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1SRqikWtR2KNpugCApreA9QeZuqh8swQMa"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(5221495),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(335),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(41),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1iKqZc4CfrPwjcD7kx8MZtFtfL6YysKnPv"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(2939210),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(189),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(23),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2DWwmauKy4Dkak6X8ePY4Z91EsM36miYxB"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1984760),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(128),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(15),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1aCb6QKL7K4JxRTUTYjAER8qZH4zKAbigq"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1866216),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(120),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(14),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1f4zxfTtjTKkrzzXNtQU73zGBcasW3xEBS"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1641573),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(106),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(12),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1TG2bxjvmRMQakt8KVQ5S6CyLzMuSHx2qF"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1502458),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(97),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1YibTr9kUchgG6wJjMwRar2NUfawxH48FT"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1459627),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(94),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1YtK9qUJffq2SqjhaJEGbufVHEBWDLPrSV"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1425001),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(91),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2DTjmLqMXSwhkpCFnV977vyhtYWbsP6nwo"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1406177),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(90),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(11),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1eaCp9cc4FtTs3Wm6UgZZnEtZ9b1Peqewi"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1322354),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(85),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(10),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1MZ7ypArEoYocyyfscGaneNKM7bADhnQC4"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(990125),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(64),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1Qzov1LwEvSfHonRHr2EwQGto7ExrH43or"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(960009),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(62),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(7),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz28e4LURT9Kv6TXysL6szWYkKKqRmA1wDGq"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(370571),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(24),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("KT1AmQTRDjTwfJDASJRJZdd7uJwDqs5W2mjA"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(289285),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(18),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1UC8X57hKRmTbgJWsoos9njMy2SW3bKAAh"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(275000),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(17),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(2),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1XX6ykvpfPGAkzeDaFPvvPqmRQoTwCvP4S"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(200001),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(13),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1P91PPAfukVdpgj153WqoLymrWDYCoyLRA"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(172996),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(11),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("KT1Kmai449TQT76GZXbihwNFHTUy432y1Z6Y"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(164629),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(10),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2JvpjaCGsynphe78Xbyu2kHUU2Ym8rxi8v"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(162848),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(10),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(1),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1YDHyB7aBCvj5TCYiRQkjeVHfgtEYUDAd2"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(63473),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(4),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1VWKeeSqxdLsTfAyCSrwFVZnfgw4ZwaHWV"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(40787),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(2),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1Xfkbwwa9ewNvYnesSXEYWGgS5gXVSQQVj"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(27475),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(1),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1Mv79qqYx2QX1NXYawrSrya13T7QoxCba9"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(8937),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("KT19XE62UbrJ2gWW4ZWq2UxTQLhrnjBHLvBm"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(826),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz2H4arakxXuzfo8NBVqTNgL5NBZ9b497Pfv"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1WxZvegEFTFSA8mqHWsBq97S15kS34JXqu"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(1),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("KT1FtGbyLR1KV9oQGEYgBUpKPkEC8BcQn4cD"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(0),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("KT1B5KPckWy2Mw99ii3wKuE4TQWKKQtSNXFE"),
				Kind:             "delegator reward",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(0),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(0),
				FeeRate:          0.11,
				Fee:              tezos.NewZ(0),
				Note:             "DELEGATOR_LOW_BALANCE",
			},
			{
				Baker:            tezos.MustParseAddress("tz1P6WKJu2rcbxKiKRZHKQKmKrpC9TfW1AwM"),
				Delegator:        tezos.Address{}, // Represents an empty delegator address
				Cycle:            1016,
				Recipient:        tezos.MustParseAddress("tz1UGkfyrT9yBt6U5PV7Qeui3pt3a8jffoWv"),
				Kind:             "donation",
				TxKind:           "tez",
				FATokenId:        tezos.NewZ(0),
				DelegatedBalance: tezos.NewZ(0),
				StakedBalance:    tezos.NewZ(0),
				Amount:           tezos.NewZ(4094),
				Fee:              tezos.NewZ(0),
				IsValid:          true,
			},
		},
	}

	assert.Equal(len(expectedResult.Payouts), len(result.Payouts))
	assert.Equal(expectedResult.Cycle, result.Cycle)
	assert.Equal(expectedResult.OwnStakedBalance, result.OwnStakedBalance)
	assert.Equal(expectedResult.OwnDelegatedBalance, result.OwnDelegatedBalance)
	assert.Equal(expectedResult.ExternalStakedBalance, result.ExternalStakedBalance)
	assert.Equal(expectedResult.ExternalDelegatedBalance, result.ExternalDelegatedBalance)
	assert.Equal(expectedResult.EarnedBlockFees, result.EarnedBlockFees)
	assert.Equal(expectedResult.EarnedRewards, result.EarnedRewards)
	assert.Equal(expectedResult.EarnedTotal, result.EarnedTotal)
	assert.Equal(expectedResult.BondIncome, result.BondIncome)
	assert.Equal(expectedResult.FeeIncome, result.FeeIncome)
	assert.Equal(expectedResult.IncomeTotal, result.IncomeTotal)
	assert.Equal(expectedResult.DonatedBonds, result.DonatedBonds)
	assert.Equal(expectedResult.DonatedFees, result.DonatedFees)
	assert.Equal(expectedResult.DonatedTotal, result.DonatedTotal)

	utils.SortPayouts(expectedResult.Payouts)
	utils.SortPayouts(result.Payouts)
	for i, payout := range expectedResult.Payouts {
		if payout.Recipient == tezos.MustParseAddress("tz1X7U9XxVz6NDxL4DSZhijME61PW45bYUJE") {
			// skip address which was used to generate test data
			// this address was used to generate test data, we do not use it in tests
			// so if it is delegated to baker it would appear in result as RECIPIENT_TARGETS_PAYOUT
			// which can not be replicated in test data as we use a random payout address for tests
			continue
		}

		assert.Equal(expectedResult.Payouts[i].Baker, result.Payouts[i].Baker)
		assert.Equal(expectedResult.Payouts[i].Delegator, result.Payouts[i].Delegator)
		assert.Equal(expectedResult.Payouts[i].Cycle, result.Payouts[i].Cycle)
		assert.Equal(expectedResult.Payouts[i].Recipient, result.Payouts[i].Recipient)
		assert.Equal(expectedResult.Payouts[i].Kind, result.Payouts[i].Kind)
		assert.Equal(expectedResult.Payouts[i].TxKind, result.Payouts[i].TxKind)
		assert.Equal(expectedResult.Payouts[i].FATokenId, result.Payouts[i].FATokenId)
		assert.Equal(expectedResult.Payouts[i].FAContract, result.Payouts[i].FAContract)
		assert.Equal(expectedResult.Payouts[i].FAAlias, result.Payouts[i].FAAlias)
		assert.Equal(expectedResult.Payouts[i].FADecimals, result.Payouts[i].FADecimals)
		assert.Equal(expectedResult.Payouts[i].DelegatedBalance, result.Payouts[i].DelegatedBalance)
		assert.Equal(expectedResult.Payouts[i].StakedBalance, result.Payouts[i].StakedBalance)
		assert.Equal(expectedResult.Payouts[i].Amount, result.Payouts[i].Amount)
		assert.Equal(expectedResult.Payouts[i].FeeRate, result.Payouts[i].FeeRate)
		assert.Equal(expectedResult.Payouts[i].Fee, result.Payouts[i].Fee)
		assert.Equal(expectedResult.Payouts[i].TxFee, result.Payouts[i].TxFee)
		assert.Equal(expectedResult.Payouts[i].Note, result.Payouts[i].Note)
		assert.Equal(expectedResult.Payouts[i].IsValid, result.Payouts[i].IsValid)
	}
}
